//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DG_DM_SHIFT
    {
        public string SHIFT_ID { get; set; }
        public string SHIFT_NAME { get; set; }
        public string SHIFT_ID_RC { get; set; }
        public short HOUR_START { get; set; }
        public short MINUTE_START { get; set; }
        public short HOUR_END { get; set; }
        public short MINUTE_END { get; set; }
        public string COMMENTS { get; set; }
        public short ACTIVE { get; set; }
        public string USER_ID { get; set; }
        public string ORGANIZATION_ID { get; set; }
        public string NEXT_SHIFT { get; set; }
    }
}
