//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_FACTORY
    {
        public string FACTORY_ID { get; set; }
        public string FACTORY_NAME { get; set; }
        public string COMMENT { get; set; }
        public string USER_ID { get; set; }
        public bool ACTIVE { get; set; }
        public string ADDRESS { get; set; }
        public string LOGO { get; set; }
        public string LOGO_NEG { get; set; }
        public string LOGO_SMALL { get; set; }
        public string PARENT_ID { get; set; }
    }
}
