//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MES_PRODUCT
    {
        public string PRODUCT_ID { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string PRODUCT_DESCRIPTION { get; set; }
        public string PRODUCT_CATEGORY_ID { get; set; }
        public string PRODUCT_UNIT { get; set; }
        public string IMG_URL { get; set; }
        public decimal CYCLE_TIME { get; set; }
        public decimal CALCULATED_CYCLE_TIME { get; set; }
        public decimal PERFORMANCE { get; set; }
        public int HEADCOUNT { get; set; }
        public bool ACTIVE { get; set; }
    }
}
