//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MES_PRODUCT_CONFIG
    {
        public string PRODUCT_CONFIG_ID { get; set; }
        public string PRODUCT_CONFIG_NAME { get; set; }
        public string DESCRIPTION { get; set; }
    }
}
