//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MES_BREAK_TIME
    {
        public string BREAK_ID { get; set; }
        public string SHIFT_ID { get; set; }
        public string BREAK_NAME { get; set; }
        public int START_HOUR { get; set; }
        public int START_MINUTE { get; set; }
        public int FINISH_HOUR { get; set; }
        public int FINISH_MINUTE { get; set; }
        public int TOTAL_MINUTE { get; set; }
        public string APPLY_LINES { get; set; }
    }
}
