//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MES_EVENTDEF
    {
        public string EVENTDEF_ID { get; set; }
        public string EVENTDEF_NAME_VN { get; set; }
        public string EVENTDEF_NAME_EN { get; set; }
        public string EVENTDEF_DESCRIPTION { get; set; }
        public string EVENTDEF_COLOR { get; set; }
        public int NUMBER_ORDER { get; set; }
        public bool USING_SOUND { get; set; }
        public string SOUND_FILENAME { get; set; }
        public string FORMULA { get; set; }
        public string DEVICE_STATUS { get; set; }
    }
}
