//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MES_CONFIGURATION
    {
        public string CONFIG_ID { get; set; }
        public string CONFIG_NAME_EN { get; set; }
        public string CONFIG_NAME_VN { get; set; }
        public int CONFIG_VALUE { get; set; }
        public string USER_ID { get; set; }
    }
}
