//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MES_LINE
    {
        public string LINE_ID { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public string FACTORY_ID { get; set; }
        public int NUMBER_ORDER { get; set; }
        public bool IS_AUTO { get; set; }
        public bool ACTIVE { get; set; }
        public string GATEWAY_ID { get; set; }
        public string LEADER_NAME { get; set; }
        public string IMG_URL { get; set; }
        public string USER_ID { get; set; }
    }
}
