//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class DM_MES_NODE_TYPE
    {
        public string NODE_TYPE_ID { get; set; }
        public string NOTE_TYPE_NAME { get; set; }
        public string DESCRIPTION { get; set; }
        public int LONG { get; set; }
        public int WIDTH { get; set; }
        public int HEIGHT { get; set; }
        public bool ACTIVE { get; set; }
        public string USER_ID { get; set; }
    }
}
