//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_MSG_NODE_EVENT
    {
        public string EVENT_ID { get; set; }
        public string NODE_ID { get; set; }
        public string EVENTDEF_ID { get; set; }
        public string EVENTDEF_NAME_VN { get; set; }
        public string EVENTDEF_NAME_EN { get; set; }
        public string EVENTDEF_COLOR { get; set; }
        public System.DateTime START { get; set; }
        public Nullable<System.DateTime> RESPONSE { get; set; }
        public Nullable<System.DateTime> FINISH { get; set; }
    }
}
