//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_TMP_PMS_DATA
    {
        public string ID { get; set; }
        public string PlanId { get; set; }
        public string ProductLineId { get; set; }
        public string PONumber { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public string Model { get; set; }
        public Nullable<int> PlanQuantity { get; set; }
        public Nullable<int> ActualQuantity { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> LastProductionTime { get; set; }
    }
}
