//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_RESPONSIBILITY
    {
        public string RESPONSIBILITY_ID { get; set; }
        public string RESPONSIBILITY_NAME_VN { get; set; }
        public string RESPONSIBILITY_NAME_EN { get; set; }
        public string DESCRIPTION { get; set; }
        public int NUMBER_ORDER { get; set; }
        public string USER_ID { get; set; }
        public bool ACTIVE { get; set; }
        public int PARENT_ID { get; set; }
    }
}
