//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_RAW_UPDATE_EVENT
    {
        public string PK_KEY { get; set; }
        public string LINE_ID { get; set; }
        public string EVENTDEF_ID { get; set; }
        public string REASON_ID { get; set; }
        public System.DateTime START_TIME { get; set; }
        public string USER_ID { get; set; }
        public short STATUS { get; set; }
    }
}
