//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_MSG_NODE_STOP
    {
        public string ID { get; set; }
        public string NODE_ID { get; set; }
        public string EVENTDEF_ID { get; set; }
        public string EVENTDEF_NAME_VN { get; set; }
        public string EVENTDEF_NAME_EN { get; set; }
        public string EVENTDEF_COLOR { get; set; }
        public string REASON_ID { get; set; }
        public string REASON_NAME_VN { get; set; }
        public string REASON_NAME_EN { get; set; }
        public decimal DURATION { get; set; }
    }
}
