//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_RAW_UPDATE_REPORT_LINE_DETAIL
    {
        public string PK_KEY { get; set; }
        public string REPORT_LINE_DETAIL_ID { get; set; }
        public string LINE_ID { get; set; }
        public string WORK_PLAN_ID { get; set; }
        public string WORK_PLAN_DETAIL_ID { get; set; }
        public string TIME_NAME { get; set; }
        public string UNIQUE_NO { get; set; }
        public decimal START_AT { get; set; }
        public decimal FINISH_AT { get; set; }
        public decimal ACTUAL_QUANTITY { get; set; }
        public decimal ACTUAL_NG_QUANTITY { get; set; }
        public short STATUS { get; set; }
        public string USER_ID { get; set; }
        public System.DateTime UPDATED { get; set; }
    }
}
