//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_LINE_TIME_PRODUTION
    {
        public string LINE_TIME_PRODUTION_ID { get; set; }
        public string LINE_ID { get; set; }
        public string LINE_CODE { get; set; }
        public string LINE_NAME { get; set; }
        public short LINE_NUMBER_ORDER { get; set; }
        public string WORK_PLAN_ID { get; set; }
        public System.DateTime DAY { get; set; }
        public string SHIFT_ID { get; set; }
        public string SHIFT_NAME { get; set; }
        public decimal PLANNING_DURATION { get; set; }
        public decimal RUNNING_DURATION { get; set; }
        public decimal STOP_DURATION { get; set; }
        public decimal BREAK_DURATION { get; set; }
        public decimal CHANGEOVER_DURATION { get; set; }
        public decimal NOPLAN_DURATION { get; set; }
        public decimal OT_1 { get; set; }
        public decimal OT_2 { get; set; }
        public decimal OT_3 { get; set; }
        public decimal OT_4 { get; set; }
        public decimal OT_5 { get; set; }
        public decimal OT_6 { get; set; }
        public decimal OUT_STOP_1 { get; set; }
        public decimal OUT_STOP_2 { get; set; }
        public decimal OUT_STOP_3 { get; set; }
        public decimal OUT_STOP_4 { get; set; }
        public decimal OUT_STOP_5 { get; set; }
        public decimal OUT_STOP_6 { get; set; }
        public decimal ACTUAL_WORKING_DURATION { get; set; }
        public short STATUS { get; set; }
    }
}
