//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_LOG_LAST_UPDATE
    {
        public string LOG_ID { get; set; }
        public string OBJECT_ID { get; set; }
        public string OBJECT_TYPE { get; set; }
        public string UPDATE_EVENT { get; set; }
        public string USER_ID { get; set; }
        public System.DateTime UPDATED { get; set; }
        public short STATUS { get; set; }
    }
}
