//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_PRODUCT_CYCLE_TIME
    {
        public string PRODUCT_CYCLE_TIME_ID { get; set; }
        public string PRODUCT_ID { get; set; }
        public string PRODUCT_CONFIG_ID { get; set; }
        public decimal CYCLE_TIME { get; set; }
        public int STATION_QUANTITY { get; set; }
        public int BATCH { get; set; }
    }
}
