//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace iAndon.Biz.Logic
{
    using System;
    using System.Collections.Generic;
    
    public partial class MES_REPORT_LINE_DETAIL
    {
        public string REPORT_LINE_DETAIL_ID { get; set; }
        public string REPORT_LINE_ID { get; set; }
        public string WORK_PLAN_ID { get; set; }
        public decimal DAY { get; set; }
        public string SHIFT_ID { get; set; }
        public string LINE_ID { get; set; }
        public string WORK_PLAN_DETAIL_ID { get; set; }
        public string WORK_ORDER_CODE { get; set; }
        public string WORK_ORDER_PLAN_CODE { get; set; }
        public string PO_CODE { get; set; }
        public string TIME_NAME { get; set; }
        public System.DateTime PLAN_START { get; set; }
        public System.DateTime PLAN_FINISH { get; set; }
        public string PRODUCT_ID { get; set; }
        public string PRODUCT_CODE { get; set; }
        public string PRODUCT_NAME { get; set; }
        public string CONFIG_ID { get; set; }
        public string CONFIG_NAME { get; set; }
        public short STATION_QUANTITY { get; set; }
        public short BATCH { get; set; }
        public decimal PLAN_TAKT_TIME { get; set; }
        public decimal PLAN_UPH { get; set; }
        public decimal PLAN_UPPH { get; set; }
        public short PLAN_HEAD_COUNT { get; set; }
        public decimal PLAN_DURATION { get; set; }
        public decimal RUNNING_TAKT_TIME { get; set; }
        public short RUNNING_HEAD_COUNT { get; set; }
        public decimal TOTAL_PLAN_QUANTITY { get; set; }
        public decimal PLAN_QUANTITY { get; set; }
        public System.DateTime STARTED { get; set; }
        public System.DateTime FINISHED { get; set; }
        public decimal ACTUAL_DURATION { get; set; }
        public decimal BREAK_DURATION { get; set; }
        public decimal STOP_DURATION { get; set; }
        public short NUMBER_OF_STOP { get; set; }
        public decimal TARGET_QUANTITY { get; set; }
        public decimal START_AT { get; set; }
        public decimal FINISH_AT { get; set; }
        public decimal ACTUAL_QUANTITY { get; set; }
        public decimal ACTUAL_NG_QUANTITY { get; set; }
        public decimal ACTUAL_TAKT_TIME { get; set; }
        public decimal ACTUAL_UPH { get; set; }
        public decimal ACTUAL_UPPH { get; set; }
        public short ACTUAL_HEAD_COUNT { get; set; }
        public decimal PLAN_RATE { get; set; }
        public decimal TARGET_RATE { get; set; }
        public decimal TIME_RATE { get; set; }
        public decimal QUALITY_RATE { get; set; }
        public decimal OEE { get; set; }
        public string RESULT { get; set; }
        public short STATUS { get; set; }
        public short DETAIL_INDEX { get; set; }
    }
}
